spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:/website}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.bookstore.readme: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
book:
  api:
    aladdin: ${BOOK_API_ALADDIN}
#    national: ${BOOK_API_NATIONAL}

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

oauth2:
  user:
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      scope: ${GOOGLE_SCOPE}
      redirect_uri: ${GOOGLE_REDIRECT_URI}
    kakao:
      client_id: ${KAKAO_CLIENT_ID}
      client_secret: ${KAKAO_CLIENT_SECRET}
      scope: ${KAKAO_SCOPE}
      redirect_uri: ${KAKAO_REDIRECT_URI}
    naver:
      client_id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      scope: ${NAVER_SCOPE}
      redirect_uri: ${NAVER_REDIRECT_URI}


jwt:
  secretKey: ${JWT_SECRET_KEY}

upload:
  locations: ${LOCAL_UPLOAD_LOCATIONS}
  path: ${LOCAL_UPLOAD_PATH}
  handler: /uploadImage/**
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:/website}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.bookstore.readme: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: off
server:
  port: 8080

oauth2:
  user:
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      scope: ${GOOGLE_SCOPE}
      redirect_uri: ${GOOGLE_REDIRECT_URI}
    kakao:
      client_id: ${KAKAO_CLIENT_ID}
      client_secret: ${KAKAO_CLIENT_SECRET}
      scope: ${KAKAO_SCOPE}
      redirect_uri: ${KAKAO_REDIRECT_URI}
    naver:
      client_id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      scope: ${NAVER_SCOPE}
      redirect_uri: ${NAVER_REDIRECT_URI}

jwt:
  secretKey: ${JWT_SECRET_KEY}

upload:
  locations: file:///readme/image/
  path: /readme/image/
  handler: /uploadImage/**
